
skillMetadata:
  sections:
    - name: Options << Name of section
      fields:
        - name: my_setting
          type: text
          label: My Setting
          value: "value_for_setting"
          placeholder: demo prompt in the input box
    - name: Login << Name of another section
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
